### PR TITLE
Allow passing schema as a second param. Tested. Closes #6.

### LINKED ISSUE #6: Refactor to use registry, and to take custom schemas
@rgrp /cc @gvidon

I'd like to suggest we make the following changes to `datapackage-validate`:

* Remove schemas submodule
* Instead, get our "official" schemas via the new [datapackage-registry module](https://github.com/okfn/datapackagist/tree/master/admin/src/scripts/components/datapackage-registry)
* Don't read from a filepath, but read a schema object. For schemas in our registry, could pass a key which is the unique id of the schema

### Goals

* Package works seamlessly in browser and server environments ([doesn't have to read a file from path](https://github.com/okfn/datapackage-validate/blob/master/index.js#L12))
* Package always stays up-to-date with changes to the core Data Package schemas
* Package has instant access to any new schemas in our [registry](https://github.com/dataprotocols/registry)
* Package can be used with any other custom Data Package schemas that a user may have

### Cons

* The only con is see is that datapackage-registry gets the "official" schemas via an API call over the web. I think it is not really a problem though - if the user does not want to rely on having a connection, that user could simply keep local copies of the schemas as part of their codebase, as we are adding the ability to load any schema

### Pros

* Because of the API call to the schemas - the official schemas are always up-to-date, and new schemas are seamlessly integrated :)

### PR DESCRIPTION
**Pull request by gvidon**
- If `schema` is an object — validate json against it
- if `schema` is a registry profile id — get schema object from registry and validate json against it
- if `schema` is empty than use default value `base` for it, get schema object from registry and validate json against it.

### CODE REVIEW

**Comment by pwalsh** [comment]
@gvidon I'm happy with this. I'm not going to merge though, as @rgrp is maintainer. So, please use your fork in DataPackagist for the moment.

**Comment by pwalsh** [comment]
@rgrp @gvidon 

Two points:

1. Do we really need to keep the `validateUrl` method? I think not.
2. I had a brief discussion with @rgrp on this because the API now uses Promises. This is why I initially hesitated to merge, as to date, other APIs in related packages used callbacks, in line with the default Node.js style. In [DataPackagist](https://github.com/okfn/datapackagist), and other new libs that result from it like [GoodTables JS](https://github.com/okfn/goodtables-js) and [DataPackage Registry](https://github.com/okfn/datapackage-registry-js) we use Promises, and I note that in Node.js land, Promises are quite widely in use now, with the [Bluebird](https://github.com/petkaantonov/bluebird) promises library, and the [Promises A+ spec](https://github.com/promises-aplus/promises-spec) which is part of [ES6](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise).
 
So, I'm suggesting we merge and publish, but probably get rid of `validateUrl` first.

**Comment by rgrp** [comment]
@pwalsh happy with whatever is your call here.

**Comment by pwalsh** [comment]
Ok so let's stick with promises, but let's use bluebird, which has nodeify and promisifyAll functions for full interop with callback code.

@gvidon:

1. Here (and elsewhere, I'll help with that) let's swap out the promises polyfill for bluebird.
2. Let's remove validateUrl in favour of a single validate API

@rgrp can you add me as a collaborator on npmjs.com so I can publish when ready (not urgent)

**Comment by gvidon** [comment]
- [x] replaced ```promise-polyfill``` with ```bluebird```
- [x] removed ```.validatrUrl()```

**Pull request merged**
